---
title: Community Charts v4 Lite
author: Matthew Leonawicz
output:
  html_document:
    toc: false
    theme: cerulean
    highlight: zenburn
    keep_md: true
---

```{r knitr_setup, echo=FALSE}
opts_chunk$set(cache=FALSE, eval=FALSE, tidy=TRUE, message=FALSE, warning=FALSE)
```

##
##
##
##
### Introduction

#### Other versions

Version 4 of the Community Charts application is documented here.
Community Charts version 4 is a lightweight application similar to version 1.
For a more powerful community charts application, see version 2, which offers much more data and interaction to the user.
Version 3 is an even more powerful and adaptive version than 2, also including more communities, data, as well as graphical and analytic capabilities.
Version 3 is currently under development as a component of the SNAP data QAQC application, which is not publicly available.

##
#### Improvements from version 1

Like the original, version 4 uses the Highcharts plotting library, but like versions 2 and 3, it is built using **R**.
Community Charts version four, also known as `CC 4 Lite`, accesses Highcharts through the **R** package, `rCharts`.
`rCharts` acts as a wrapper to a number of external plotting libraries, but the intent here is to make a Community Charts application similar to the original, hence the focus on Highcharts.
At the same, it is important to improve upon the original, which can be criticized on a number of poor graphing practices and other uses of descriptive statistics.
Some improvements are considered here, addressing criticisms of historical baseline data sources, temporal periods, bar plot baseline thresholds, color usage, and uncertainty among climate models.

##
#### New features and data sources

In additional to a critical look at the original version, critical evaluations of newly considered chart features and data are also needed.
New communities are intended to be added to the application, but for which data only exist at a much coarser resolution compared to the originally included communities.
This mixture of disparate data sources must be clearly noted in the application of course.

However, this is not enough. To stop here is amateurish and not justifiable.
At a bare minimum, it is crucial that the effect of spatial scale on climate data in this context be investigated.
It is possible that climate estimates differ enough between scales such that allowing some communities to use data exclusively at one scale and others at the alternative scale ought to be prohibited from the application entirely.

The two scales are the original 2-km resolution and the coarser 10-minute resolution under consideration.
The former originates from SNAP's downscaled climate data based on the 2-km PRISM climatology and the latter from data downscaled using the 10-minute CRU climatology.

Version 4, like version 3, will feature the inclusion of CMIP5 downscaled climate model outputs.
Since version 4 is meant to be lightweight like version 1, it will not include CMIP3 outputs as well like versions 2 and 3.

##
##
### Motivation

There are several benefits to updating the Community Charts application.
Most notably, older downscaled climate model outputs can be swapped out for more updated outputs.

##
#### Communities

A new version also presents an opportunity to update the communities data set.
This means not only including new communities (not ignoring the necessary invesitgation noted above),
but more importantly a chance to clean up and refactor the original set of communities.
These currently represent a very messy data set, including communites with several duplicate listing (which actually show up in the original application) and "communities" with populations of size zero.
Some of these are essentially campsites and only serve to clutter the application and enlongate the community selection menu. More is not necessarily better, especially if it presents poorly.

##
#### Appearance and function

Third, improvements can be made to the graphs themselves as mentioned above.
Fourth, new options available to the user for interacting with the graphs may be considered.

##
#### Community Charts as QAQC

Although this is more true of version 3, version 4 of the Community Charts application is also a practical use case for extracted data which serves as an extension of SNAP data QAQC procedures.
In fact, the **R** code used to extract data from some of SNAP's core spatially explicit data sets as a fundamental component of my ongoing SNAP data QAQC project provide the very data used by this application.
